name: 'Zhen AI Code Review'
description: 'AI驱动的代码审查工具，使用OpenAI自动审查PR代码并发表中文评论'
author: 'zhenzhenxu'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: true
  github_token:
    description: 'GitHub Token（用于发表评论）'
    required: false
    default: ${{ github.token }}
  openai_model:
    description: 'OpenAI 模型名称'
    required: false
    default: 'gpt-4o'
  language:
    description: '输出语言：zh（中文）或 en（英文）'
    required: false
    default: 'zh'
  post_comment:
    description: '是否在PR上发表评论'
    required: false
    default: 'true'
  exclude_patterns:
    description: '排除的文件模式（逗号分隔），如：*.md,*.txt'
    required: false
    default: '*.md,*.txt,*.json,*.lock,*.yml,*.yaml'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      shell: bash
      run: |
        pip install -q openai PyGithub click python-dotenv rich pydantic gitpython

    - name: Run AI Code Review
      shell: bash
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_MODEL: ${{ inputs.openai_model }}
        REVIEW_LANGUAGE: ${{ inputs.language }}
        POST_COMMENT: ${{ inputs.post_comment }}
        EXCLUDE_PATTERNS: ${{ inputs.exclude_patterns }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        python ${{ github.action_path }}/scripts/review_pr.py
